name: Deploy to Google Play

on:
  workflow_dispatch:
    inputs:
      track:
        description: 'Google Play release track'
        required: true
        default: 'internal'
        type: choice
        options:
          - internal
          - alpha
          - beta
          - production
      release_status:
        description: 'Release status'
        required: true
        default: 'completed'
        type: choice
        options:
          - draft
          - completed
  release:
    types: [published]

permissions:
  contents: read

env:
  TRACK: ${{ github.event.inputs.track || 'internal' }}
  RELEASE_STATUS: ${{ github.event.inputs.release_status || 'completed' }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Get version info
        id: version
        run: |
          version=$(cat VERSION | tr -d '\n')
          echo "version=$version" >> $GITHUB_OUTPUT

          # Extract version components for versionCode calculation
          IFS='.' read -r major minor patch <<< "${version%-*}"
          # Remove any non-numeric characters from patch
          patch=$(echo "$patch" | sed 's/[^0-9].*//')

          # Calculate version code: major*10000 + minor*100 + patch
          version_code=$((major * 10000 + minor * 100 + patch))
          echo "version_code=$version_code" >> $GITHUB_OUTPUT

          echo "App Version: $version"
          echo "Version Code: $version_code"

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Decode keystore
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 -d > app/release-keystore.jks
          chmod 600 app/release-keystore.jks

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Release APK
        run: |
          ./gradlew assembleRelease --no-daemon \
            -Pandroid.injected.signing.store.file=${{ github.workspace }}/app/release-keystore.jks \
            -Pandroid.injected.signing.store.password=${{ secrets.ANDROID_KEYSTORE_PASSWORD }} \
            -Pandroid.injected.signing.key.alias=${{ secrets.ANDROID_KEY_ALIAS }} \
            -Pandroid.injected.signing.key.password=${{ secrets.ANDROID_KEY_PASSWORD }}

      - name: Verify APK was signed
        run: |
          apk_path=$(find app/build/outputs/apk/release -name "*.apk" -type f | head -n1)
          if [ -z "$apk_path" ]; then
            echo "Error: No APK found"
            exit 1
          fi

          echo "Found APK: $apk_path"

          # Verify the APK is signed
          if command -v apksigner &> /dev/null; then
            apksigner verify --print-certs "$apk_path" || echo "Note: apksigner not available for verification"
          fi

      - name: Generate release notes
        id: release_notes
        run: |
          version="${{ steps.version.outputs.version }}"

          # Create whatsnew directory for Google Play
          mkdir -p whatsnew

          # Get last tag for changelog
          git fetch --tags
          last_tag=$(git tag --sort=-creatordate | head -n1)

          if [ -n "$last_tag" ]; then
            log_range="$last_tag..HEAD"
          else
            log_range=""
          fi

          # Collect features and fixes
          features=$(git log $log_range --pretty=format:"%s" 2>/dev/null | grep -E '^feat(\(.+\))?:' | sed 's/^feat(\([^)]*\)): /• \1: /' | sed 's/^feat: /• /' | head -5 || true)
          fixes=$(git log $log_range --pretty=format:"%s" 2>/dev/null | grep -E '^fix(\(.+\))?:' | sed 's/^fix(\([^)]*\)): /• \1: /' | sed 's/^fix: /• /' | head -5 || true)

          # Build release notes (max 500 chars for Google Play)
          {
            echo "What's New in v${version}:"
            echo ""

            if [ -n "$features" ]; then
              echo "$features"
            fi

            if [ -n "$fixes" ]; then
              echo "$fixes"
            fi

            # If no features or fixes, add a default message
            if [ -z "$features" ] && [ -z "$fixes" ]; then
              echo "• General improvements and bug fixes"
            fi
          } > whatsnew/whatsnew-en-US

          # Truncate to 500 characters (Google Play limit)
          head -c 500 whatsnew/whatsnew-en-US > whatsnew/temp && mv whatsnew/temp whatsnew/whatsnew-en-US

          echo "Release notes generated:"
          cat whatsnew/whatsnew-en-US

      - name: Upload to Google Play Console
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_JSON }}
          packageName: com.nesventory.android
          releaseFiles: app/build/outputs/apk/release/*.apk
          track: ${{ env.TRACK }}
          status: ${{ env.RELEASE_STATUS }}
          releaseName: v${{ steps.version.outputs.version }}
          whatsNewDirectory: whatsnew

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v5
        with:
          name: release-apk-${{ steps.version.outputs.version }}
          path: app/build/outputs/apk/release/*.apk
          retention-days: 90

      - name: Cleanup keystore
        if: always()
        run: |
          rm -f app/release-keystore.jks

      - name: Summary
        run: |
          echo "## Deploy Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- **Version**: v${{ steps.version.outputs.version }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Version Code**: ${{ steps.version.outputs.version_code }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Track**: ${{ env.TRACK }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Status**: ${{ env.RELEASE_STATUS }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "APK has been uploaded to Google Play Console." >> $GITHUB_STEP_SUMMARY
