name: Update Release Notes

on:
  pull_request:
    types: [closed]
    branches:
      - main

permissions:
  contents: write

jobs:
  update-release-notes:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ref: main

      - name: Get current version
        id: version
        run: |
          version=$(cat VERSION | tr -d '\n')
          echo "version=$version" >> $GITHUB_OUTPUT

          # Parse version components
          IFS='.' read -r major minor patch <<< "$version"
          echo "major=$major" >> $GITHUB_OUTPUT
          echo "minor=$minor" >> $GITHUB_OUTPUT
          echo "patch=$patch" >> $GITHUB_OUTPUT

      - name: Get last tag
        id: last_tag
        run: |
          git fetch --tags
          tag=$(git tag --sort=-creatordate | head -n1)
          echo "last_tag=$tag" >> $GITHUB_OUTPUT

      - name: Generate release notes content
        id: notes
        run: |
          version="${{ steps.version.outputs.version }}"
          last_tag="${{ steps.last_tag.outputs.last_tag }}"

          # Determine log range
          if [ -z "$last_tag" ]; then
            log_range=""
          else
            log_range="$last_tag..HEAD"
          fi

          # Start building release notes
          {
            echo "# Android-NesVentory v${version} Release Notes"
            echo ""
            echo "## Overview"
            echo ""
            echo "Android companion app for NesVentory - Version ${version}"
            echo ""
          } > RELEASE_NOTES.md

          # Collect commits by type
          features=$(git log $log_range --pretty=format:"%s" 2>/dev/null | grep -E '^feat(\(.+\))?:' | sed 's/^feat(\([^)]*\)): /- **\1**: /' | sed 's/^feat: /- /' || true)
          fixes=$(git log $log_range --pretty=format:"%s" 2>/dev/null | grep -E '^fix(\(.+\))?:' | sed 's/^fix(\([^)]*\)): /- **\1**: /' | sed 's/^fix: /- /' || true)
          breaking=$(git log $log_range --pretty=format:"%s" 2>/dev/null | grep -iE '^(breaking change|BREAKING CHANGE)' || true)
          deps=$(git log $log_range --pretty=format:"%s" 2>/dev/null | grep -iE '^(chore\(deps\)|build\(deps\)|Bump .+ from .+ to)' | sed 's/^chore(deps): //' | sed 's/^build(deps): //' | sed 's/^/- /' || true)

          # Add New Features section
          if [ -n "$features" ]; then
            {
              echo "## New Features"
              echo ""
              echo "$features"
              echo ""
            } >> RELEASE_NOTES.md
          fi

          # Add Bug Fixes section
          if [ -n "$fixes" ]; then
            {
              echo "## Bug Fixes"
              echo ""
              echo "$fixes"
              echo ""
            } >> RELEASE_NOTES.md
          fi

          # Add Breaking Changes section
          if [ -n "$breaking" ]; then
            {
              echo "## Breaking Changes"
              echo ""
              echo "$breaking" | sed 's/^/- /'
              echo ""
            } >> RELEASE_NOTES.md
          else
            {
              echo "## Breaking Changes"
              echo ""
              echo "None"
              echo ""
            } >> RELEASE_NOTES.md
          fi

          # Add Dependency Updates section
          if [ -n "$deps" ]; then
            {
              echo "## Dependency Updates"
              echo ""
              echo "$deps"
              echo ""
            } >> RELEASE_NOTES.md
          fi

          # Add footer
          {
            echo "---"
            echo ""
            echo "See complete PRs: https://github.com/${{ github.repository }}/pulls?q=is%3Apr+is%3Aclosed"
          } >> RELEASE_NOTES.md

          echo "Release notes generated for v${version}"

      - name: Commit and push release notes
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

          # Check if RELEASE_NOTES.md has changes
          if git diff --quiet RELEASE_NOTES.md; then
            echo "No changes to RELEASE_NOTES.md"
          else
            git add RELEASE_NOTES.md
            git commit -m "docs: update RELEASE_NOTES.md for v${{ steps.version.outputs.version }}"
            git push
          fi
